version: 0.2

phases:
  post_build:
    commands:
      - echo '{"cluster":"cluster", "rollback_on_fail":false, "deployment":"sample-app", "containers":[{"tag":"latest","container_name":"app"}], "namespace":"default"}' > deployer_config.json

artifacts:
  files:
      - deployer_config.json