apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lambda-deployer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lambda-deployer
subjects:
  - kind: ServiceAccount
    # The aws-auth configmap must be updated to map the Lambda's role ARN to this serviceaccount
    # In this case, the group under mapRoles is "system:serviceaccount:lambda-deployer"
    namespace: default
    name: lambda-deployer
roleRef:
  kind: ClusterRole
  name: lambda-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lambda-deployer